### ISSUE TITLE
what happened to System.IO.UTF8 ?

### ISSUE THREAD

**Issue by jwaldmann** [glguy/utf8-string#10]
apparently this module vanished when the version jumped from 0.3.8 to 1

```
    Could not find module ‘System.IO.UTF8’
    It is a member of the hidden package ‘utf8-string-0.3.8’.
    Perhaps you need to add ‘utf8-string’ to the build-depends in your .cabal file.
```

**Comment by glguy** [comment]
This module existed to support versions of GHC before 6.10 that did not support UTF-8. It is no longer necessary.

**Comment by jwaldmann** [comment]
This means I should replace the import of this module by what? Prelude?

**Comment by glguy** [comment]
System.IO
