### ISSUE TITLE
Optimise Data.ByteString.Lazy.UTF8.fromString

### ISSUE THREAD

**Issue by ndmitchell** [glguy/utf8-string#12]
In benchmarking Hoogle I found that Lazy.UTF8.fromString was a bottleneck, so I wrote an optimised version. It's at https://github.com/ndmitchell/hoogle/blob/master/src/General/Str.hs#L90. QuickCheck shows it to be equivalent, at least as far as the QuickCheck String generator works. My benchmarks suggest my version is more than twice as fast on my data, but if you want to take this version, it should be properly benchmarked. Mine has the advantage of being lazy (I don't think yours is, but I'm not sure). The only downside is that it allocates 1024 byte bytestrings each time, so for the final chunk or for short bytestrings there will be some memory wastage - but that could be avoided with a BS.copy.

**Comment by ndmitchell** [comment]
With the benchmark:

    import System.IO.Extra
    import Control.Monad
    import General.Str
    import qualified Data.ByteString.Lazy.Char8 as LBS
    import Control.Exception
    import qualified Data.ByteString.Lazy.UTF8 as UTF8
    import System.Time.Extra
    import Control.DeepSeq

    main :: IO ()
    main = do
        src <- readFileUTF8 "test.txt"
        evaluate $ rnf src
        forM_ [lstrPack, UTF8.fromString, LBS.pack] $ \f -> do
            (t,_) <- duration $ forM_ ['\1'..'\100000'] $ \c -> do
                evaluate $ rnf $ f $ c:src
            print t

Using the file `test.txt` being the W3C UTF-8 test file from http://www.w3.org/2001/06/utf-8-test/postscript-utf-8.html (mostly ASCII, a little bit of unicode - so probably quite representative of real life), GHC 7.10.2 -O2 I got the timings:

* lstrPack (my new one) 3.0729648
* UTF8.fromString 18.5217108
* LBS.pack 3.4221276

So with that technique, my UTF8 encoder actually outperforms a simple byte-string pack (by 10% or so), but is 6x faster than UTF8.fromString.

Full disclosure, taking the worst-case for this algorithm (a single character taking up 4 bytes when UTF8 encoded) my version is 2x slower than UTF8.fromString. But I suspect peering at the GHC Core would probably fix that, and in normal cases it should win easily.

**Comment by glguy** [comment]
I'd be happy to merge in code to make the common case for encoding UTF-8 faster.

The existing `fromString` is lazy as it's simply implemented by encoding to a String first (which is lazy) and then calling lazy bytestring's `pack` which lazily produces chunks (which grow by a factor of 2 up to the smallChunkSize)

**Comment by ndmitchell** [comment]
I should probably read the Lazy pack code more closely, I suspect I got it confused with the strict pack code. I should probably also follow the doubling algorithm of byte string, for consistency and for guaranteed performance increases (it would basically amount to a manual list fusion). I'll work on a pull request this weekend.

**Comment by ndmitchell** [comment]
Reading the code for lazy pack shows why I'm faster than they are - I have a single increment in my inner loop, while they have an increment of the pointer and a decrement of the size left. It also shows where I have additional overhead (in the IO machinery, and my chunks are actually shorter and with less garbage).
