### ISSUE TITLE
utf8-string-1.0.1 broken on GHC 7.0

### ISSUE THREAD

**Issue by hvr** [glguy/utf8-string#14]
...why u no travis-ci? =)

```
[4 of 5] Compiling Data.ByteString.Lazy.UTF8 ( Data/ByteString/Lazy/UTF8.hs, dist/dist-sandbox-8ba05379/build/Data/ByteString/Lazy/UTF8.o )

Data/ByteString/Lazy/UTF8.hs:278:26:
    Not in scope: `unsafeDupablePerformIO'
```

for versions prior to GHC 7.2/base-4.4, you can find `unsafeDuablePerformIO` in `GHC.IO`

PS: I've fixed up the `base`-bound on https://hackage.haskell.org/package/utf8-string-1.0.1/revisions/

**Comment by glguy** [comment]
>    ...why u no travis-ci? =) 

Fixed in f9a62f3fc9104fcc2fa8960cf3a00d23b9604c8c
