### ISSUE TITLE
Data.ByteString.Lazy.UTF8.fromString surprising behavior

### ISSUE THREAD

**Issue by jimcrayne** [glguy/utf8-string#18]
I find this behavior surprising:
```
> import qualified  Data.ByteString.Lazy.Char8 as L
> import qualified  Data.ByteString.Lazy.UTF8 as U
> ("x→y"::U.ByteString)
"x\146y"
> ("x→y"::L.ByteString)
"x\146y"
> ("x→y"::String)
"x\8594y"
> putStrLn ("x→y"::String)
x→y
> L.putStrLn ("x→y"::U.ByteString)
x�y
```

In particular, why should U.fromString be completely equivalent to L.fromString? Since the whole point of fromString is to let us write literals like this...

Note that we can finesse the L.putStrLn to work by converting to unicode:
```
> import Data.Binary
> L.putStrLn (L.drop 8 . encode $ "x→y")
x→y
```

**Comment by glguy** [comment]
The utf8-string package doesn't define a new ByteString type and it has nothing to do with the OverloadedStrings extension. U.fromString is not identical to L.fromString. Note the following output:

```
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> import qualified  Data.ByteString.Lazy.Char8 as L
Prelude L> import qualified  Data.ByteString.Lazy.UTF8 as U
Prelude L U> L.putStrLn (U.fromString "x→y")
x→y
```

This "fromString" function predates the existence of the IsString class.

**Comment by jimcrayne** [comment]
I see. I do still think, however, that this is unfortunate, and since I see no better solution, I recommend it be more explicitly documented in the haddock.
