### ISSUE TITLE
Latest release on hackage doesn't install with HP 8.0.2

### ISSUE THREAD

**Issue by wjt** [glguy/utf8-string#21]
The latest release on Hackage has:

```
  build-depends: base >= 4.3 && < 4.9, bytestring >= 0.9
```

Haskell Platform 8.0.2 has base-4.9.1.0.

I see the dependency has been bumped in master, any chance of a release?

**Comment by glguy** [comment]
You must be looking in the wrong place. The bounds have been revised to build with GHC as recently as 8.2.1-rc3. See http://hackage.haskell.org/package/utf8-string

**Comment by wjt** [comment]
https://hackage.haskell.org/package/utf8-string shows (to me) that 1.0.1.1 is the latest version.
```
  gelf /tmp
% wget https://hackage.haskell.org/package/utf8-string-1.0.1.1/utf8-string-1.0.1.1.tar.gz
[...]
  gelf /tmp
% tar -xzf utf8-string-1.0.1.1.tar.gz
  gelf /tmp
% grep build-depends utf8-string-1.0.1.1/utf8-string.cabal
  build-depends: base >= 4.3 && < 4.9, bytestring >= 0.9
```

Something funky is going on because if I click the "Package description" link on https://hackage.haskell.org/package/utf8-string – which leads to https://hackage.haskell.org/package/utf8-string-1.0.1.1/utf8-string.cabal – I see:

```
  build-depends: base >= 4.3 && < 4.11, bytestring >= 0.9
```

If I follow the "Browse" link and click through to https://hackage.haskell.org/package/utf8-string-1.0.1.1/src/utf8-string.cabal I see:

```
  build-depends: base >= 4.3 && < 4.9, bytestring >= 0.9
```

**Comment by wjt** [comment]
`cabal get -v3 utf8-string` shows that it is fetching http://hackage.haskell.org/package/utf8-string-1.0.1.1/utf8-string-1.0.1.1.tar.gz

And yet: the contents of utf8-string.cabal differ depending on whether I unpack it with `cabal get` or with `tar`:

```
  gelf ~/a
% cabal get utf8-string
Downloading utf8-string-1.0.1.1...
Unpacking to utf8-string-1.0.1.1/
  gelf ~/a
% grep base utf8-string-1.0.1.1/utf8-string.cabal
  build-depends: base >= 4.3 && < 4.11, bytestring >= 0.9
  gelf ~/a
% mkdir ../b
  gelf ~/a
% cd ../b
  gelf ~/b
% tar xzf ~/.cabal/packages/hackage.haskell.org/utf8-string/1.0.1.1/utf8-string-1.0.1.1.tar.gz 
  gelf ~/b
% grep base utf8-string-1.0.1.1/utf8-string.cabal
  build-depends: base >= 4.3 && < 4.9, bytestring >= 0.9
```

The other difference is:

```
x-revision: 2
```

In the copy unpacked by `cabal get`.

**Comment by wjt** [comment]
Okay, so the revised copy comes from the Hackage index. To me it seems surprising that the source tarball linked from the Hackage page is not the same source that I get by fetching the package with `cabal` but maybe this is expected?
