### ISSUE TITLE
utf8-string-1.0.1.1 doesn't declare MultiParamTypeClasses extension

### ISSUE THREAD

**Issue by peti** [glguy/utf8-string#22]
utf8-string-1.0.1.1 fails to compile with GHC 7.4.1 because of the  following issue:

~~~
Codec/Binary/UTF8/Generic.hs:48:1:
    Too many parameters for class `UTF8Bytes'
    (Use -XMultiParamTypeClasses to allow multi-parameter classes)
    In the class declaration for `UTF8Bytes'
~~~

**Comment by glguy** [comment]
@peti It looks to me like that module already uses the MultiParamTypeClasses extension. Additionally, I don't support GHC 7.4.1. Does this work on 7.4.2?

**Comment by peti** [comment]
The error *did* occur with GHC 7.4.2. Sorry, I had a typo in the version number in my original message.

**Comment by glguy** [comment]
In that case I can't reproduce the problem. The code on hackage for this version already has the language pragma.

**Comment by glguy** [comment]
Yeah, it does seem likely to be a Haddock bug that has since been fixed.
