### ISSUE TITLE
Consider adding property-based roundtrip tests for decode/encode

### ISSUE THREAD

**Issue by ChShersh** [glguy/utf8-string#27]
There was raised some concern about differences between `encodeUtf8/decodeUtf8` from the `text` package and `encodeUtf8/decodeUtf8` package.

* https://github.com/kowainik/relude/pull/104

Here you can see the results of the tests:

* https://github.com/kowainik/relude/pull/104#issuecomment-430751464

And here are the tests themselves implemented by @sphaso:

* https://github.com/sphaso/serialization-benchmark/blob/master/test/test.hs

Using `text` package directly significantly improves the speed of UTF8 conversion. but the result is different from the `utf8-string` package on some cases (which is worrying). I wonder, what can be done here:

1. Improve performance of the `utf8-string` package
2. Fix errors in `text` package

**Comment by glguy** [comment]
@ChShersh I would recommend using the text package. The utf8-string package predates GHC having Unicode IO support and the text package existing. The text package is what I use.

**Comment by glguy** [comment]
@ChShersh utf8-string already has exhaustive tests for valid encodings and negative tests for classes of invalid encodings, property-based tests wouldn't add anything new.

https://github.com/glguy/utf8-string/blob/f1e251439c774b6a786b17892af7f43c05a59114/tests/Tests.hs

**Comment by ChShersh** [comment]
@glguy Thanks for the quick and informative update on this!
