### ISSUE TITLE
withArgs leads to a recoverEncode error on Windows

### ISSUE THREAD

**Issue by ndmitchell** [glguy/utf8-string#7]
C:\Neil>ghci
    GHCi, version 7.6.1: http://www.haskell.org/ghc/  :? for help
    Prelude> import System.Environment.UTF8
    Prelude System.Environment.UTF8> withArgs ["\x263A"] $ return ()
    Loading package utf8-string-0.3.7 ... linking ... done.
    *** Exception: recoverEncode: invalid argument (invalid character)

It seems withArgs just calls the underlying withArgs. Should it be encoding the strings first? GHC 7.6.1 on Windows.

**Comment by glguy** [comment]
The IO wrappers are a remnant of GHC 6.10 and have been removed in the latest 1 release
